const translations={
  en:{
    "nav.about":"About","nav.skills":"Skills","nav.projects":"Projects","nav.experience":"Experience","nav.education":"Education","nav.certifications":"Certifications","nav.contact":"Contact",
    "hero.eyebrow":"Hi, I'm","hero.role":"Computer Science & Networks Engineering Student","hero.text":"4th-year Computer Science & Networks Engineering student at EMSI, Morocco.","hero.projects":"View projects","hero.contact":"Contact me",
    "about.eyebrow":"About me","about.title":"Engineering student, developer and creative thinker.","about.text":"I'm a Computer Science & Networks Engineering student at EMSI. I enjoy web development, databases and building useful applications. My academic projects and internship at AMTIC gave me practical experience with Laravel, PHP, Django, Python, MySQL, JavaScript and Git. Beyond code, I also love writing: it's how I explore and express ideas.",
    "info.location":"Location","info.school":"School","info.specialization":"Focus","skills.eyebrow":"My tools","skills.title":"Skills & technologies","skills.programming":"Programming","skills.web":"Web","skills.db":"Databases","skills.tools":"Tools & modeling",
    "projects.eyebrow":"Selected work","projects.title":"My projects","filters.all":"All","filters.web":"Web","filters.desktop":"Desktop","filters.ai":"AI","filters.internship":"Internship",
    "project.readora.desc":"Digital university library with a vocal and text AI assistant.","project.readora.role":"Contribution: assistant development and participation in frontend & backend.",
    "project.gmao.desc":"Maintenance management platform for equipment, interventions and costs.","project.gmao.role":"Contribution: backend development.",
    "project.linkpro.desc":"Professional digital identity platform improved during my internship at AMTIC.","project.linkpro.role":"Contribution: interface and assigned feature improvements.",
    "project.sports.desc":"Web application for booking sports fields and equipment.","project.sports.role":"Contribution: frontend development.","project.timetable.desc":"Desktop application for managing student and professor schedules.","project.bio.desc":"Application connecting neighbors around organic products.","project.bio.role":"Contribution: main flow and class structure.","project.converter.desc":"Desktop tool for converting different units.","common.details":"View details →",
    "experience.eyebrow":"Professional experience","experience.title":"Internship at AMTIC","experience.role":"Web Development Intern","experience.date":"July 1 – August 7, 2026 · 5 weeks","experience.intro":"Contributed to the evolution of LinkPro, a professional digital identity platform.","experience.t1":"Integrated an image into the Pricing section.","experience.t2":"Created separate pages for public menu items.","experience.t3":"Improved the Templates page.","experience.t4":"Implemented dynamic user profile image display.","experience.t5":"Created the template_categories table.","experience.t6":"Worked on an assistant feature.",
    "education.eyebrow":"Academic journey","education.title":"Education","education.degree":"Engineering Degree — Computer Science & Networks","education.school":"École Marocaine des Sciences de l'Ingénieur","education.current":"Currently studying",
    "certs.eyebrow":"Learning & credentials","certs.title":"Certifications","contact.eyebrow":"Let's connect","contact.title":"Have a project in mind or an opportunity to discuss?","contact.subtitle":"Feel free to contact me.","form.name":"Name","form.email":"Email","form.message":"Message","form.send":"Send message","form.note":"Your email application will open with the message prepared.","footer.text":"Designed & built by Fatima-Ezzahrae Jami · © 2026","modal.tech":"Technologies","modal.contribution":"Contribution"
  },
  fr:{
    "nav.about":"À propos","nav.skills":"Compétences","nav.projects":"Projets","nav.experience":"Expérience","nav.education":"Formation","nav.certifications":"Certifications","nav.contact":"Contact",
    "hero.eyebrow":"Bonjour, moi c'est","hero.role":"Étudiante ingénieure en informatique et réseaux","hero.text":"Étudiante en 4ᵉ année d'ingénierie informatique et réseaux à l'EMSI, Maroc.","hero.projects":"Voir mes projets","hero.contact":"Me contacter",
    "about.eyebrow":"À propos de moi","about.title":"Étudiante ingénieure, développeuse et passionnée par la création.","about.text":"Je suis étudiante en ingénierie informatique et réseaux à l'EMSI. Je m'intéresse au développement web, aux bases de données et à la conception d'applications utiles. Mes projets académiques et mon stage chez AMTIC m'ont permis de travailler avec Laravel, PHP, Django, Python, MySQL, JavaScript et Git. Au-delà du code, j'aime aussi écrire : c'est ma manière d'explorer et d'exprimer mes idées.",
    "info.location":"Localisation","info.school":"École","info.specialization":"Domaine","skills.eyebrow":"Mes outils","skills.title":"Compétences & technologies","skills.programming":"Programmation","skills.web":"Web","skills.db":"Bases de données","skills.tools":"Outils & modélisation",
    "projects.eyebrow":"Travaux sélectionnés","projects.title":"Mes projets","filters.all":"Tous","filters.web":"Web","filters.desktop":"Desktop","filters.ai":"IA","filters.internship":"Stage",
    "project.readora.desc":"Bibliothèque universitaire numérique avec assistant IA vocal et textuel.","project.readora.role":"Contribution : développement de l'assistant et participation au frontend & backend.",
    "project.gmao.desc":"Plateforme de gestion de maintenance des équipements, interventions et coûts.","project.gmao.role":"Contribution : développement backend.",
    "project.linkpro.desc":"Plateforme d'identité numérique professionnelle améliorée pendant mon stage chez AMTIC.","project.linkpro.role":"Contribution : amélioration de l'interface et des fonctionnalités assignées.",
    "project.sports.desc":"Application web de réservation de terrains et d'équipements sportifs.","project.sports.role":"Contribution : développement frontend.","project.timetable.desc":"Application desktop de gestion des emplois du temps des étudiants et professeurs.","project.bio.desc":"Application mettant en relation des voisins autour de produits biologiques.","project.bio.role":"Contribution : développement du flux principal et participation à la structure des classes.","project.converter.desc":"Outil desktop de conversion de différentes unités.","common.details":"Voir les détails →",
    "experience.eyebrow":"Expérience professionnelle","experience.title":"Stage chez AMTIC","experience.role":"Stagiaire en développement web","experience.date":"1 juillet – 7 août 2026 · 5 semaines","experience.intro":"Participation à l'évolution de LinkPro, une plateforme d'identité numérique professionnelle.","experience.t1":"Intégration d'une image dans la section Pricing.","experience.t2":"Création de pages séparées pour les éléments du menu public.","experience.t3":"Amélioration de la page Templates.","experience.t4":"Affichage dynamique de l'image de profil utilisateur.","experience.t5":"Création de la table template_categories.","experience.t6":"Travail sur une fonctionnalité d'assistant.",
    "education.eyebrow":"Parcours académique","education.title":"Formation","education.degree":"Cycle ingénieur — Informatique & Réseaux","education.school":"École Marocaine des Sciences de l'Ingénieur","education.current":"En cours",
    "certs.eyebrow":"Apprentissage & certifications","certs.title":"Certifications","contact.eyebrow":"Restons en contact","contact.title":"Un projet ou une opportunité à discuter ?","contact.subtitle":"N'hésitez pas à me contacter.","form.name":"Nom","form.email":"Email","form.message":"Message","form.send":"Envoyer le message","form.note":"Votre application de messagerie s'ouvrira avec le message préparé.","footer.text":"Conçu et développé par Fatima-Ezzahrae Jami · © 2026","modal.tech":"Technologies","modal.contribution":"Contribution"
  }
};

const projects={
  readora:{logo:'assets/images/logoreadora.png',meta:{en:'2026 · Academic',fr:'2026 · Académique'},desc:{en:'Digital university library with a vocal and text AI assistant.',fr:'Bibliothèque universitaire numérique avec assistant IA vocal et textuel.'},role:{en:'Assistant development and participation in frontend & backend.',fr:"Développement de l'assistant et participation au frontend & backend."},tech:['Django','Python','HTML','CSS','JavaScript','SQLite'],images:[['assets/images/readora-login.png','Login interface','Interface de connexion'],['assets/images/readora-assistant.png','AI assistant interface','Interface de l’assistant IA']],link:null},
  gmao:{logo:null,meta:{en:'2026 · Academic',fr:'2026 · Académique'},desc:{en:'Maintenance management platform for equipment, interventions and costs.',fr:'Plateforme de gestion de maintenance des équipements, interventions et coûts.'},role:{en:'Backend development.',fr:'Développement backend.'},tech:['Django','Python','MySQL','HTML','CSS','JavaScript'],images:[['assets/images/gmao1.png','GMAO interface 1','Interface GMAO 1'],['assets/images/gmao2.png','GMAO interface 2','Interface GMAO 2']],link:'https://github.com/fatimaezzahraejami185-eng/gmao-django'},
  linkpro:{logo:'assets/images/logolinkpro.png',meta:{en:'2026 · AMTIC internship',fr:'2026 · Stage AMTIC'},desc:{en:'Professional digital identity platform improved during my internship at AMTIC.',fr:"Plateforme d'identité numérique professionnelle améliorée pendant mon stage chez AMTIC."},role:{en:'Interface and assigned feature improvements.',fr:"Amélioration de l'interface et des fonctionnalités assignées."},tech:['Laravel','PHP','MySQL','HTML','CSS','JavaScript','Git'],images:[['assets/images/linkpro1.png','LinkPro interface 1','Interface LinkPro 1'],['assets/images/linkpro2.png','LinkPro interface 2','Interface LinkPro 2']],link:'https://github.com/ag-abderrahim/linkpro/tree/fati-dev'}
};

let currentLang=localStorage.getItem('portfolioLang')||'fr';
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function setLanguage(lang){currentLang=lang;localStorage.setItem('portfolioLang',lang);document.documentElement.lang=lang;$$('[data-i18n]').forEach(el=>{const value=translations[lang][el.dataset.i18n];if(value)el.textContent=value});$$('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));}
$$('.lang').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
const menu=$('.menu-toggle'),nav=$('.nav-links');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{ $$('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const filter=btn.dataset.filter;$$('.project-card').forEach(card=>{const show=filter==='all'||card.dataset.category.split(' ').includes(filter);card.hidden=!show;});}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(el=>observer.observe(el));

const modal=$('#projectModal'), screenshots=$('#modalScreenshots'), modalLogo=$('#modalLogo'), modalLink=$('#modalLink');
function openProject(id){const p=projects[id];$('#modalMeta').textContent=p.meta[currentLang];$('#modalTitle').textContent=id==='readora'?'READORA':id==='gmao'?'GMAO':'LinkPro';$('#modalDescription').textContent=p.desc[currentLang];$('#modalContribution').textContent=p.role[currentLang];$('#modalTech').innerHTML=p.tech.map(t=>`<span>${t}</span>`).join('');
  screenshots.innerHTML=p.images.map(img=>`<figure><img src="${img[0]}" alt="${currentLang==='fr'?img[2]:img[1]}"><figcaption>${currentLang==='fr'?img[2]:img[1]}</figcaption></figure>`).join('');
  if(p.logo){modalLogo.src=p.logo;modalLogo.alt=id==='readora'?'Logo READORA':'Logo LinkPro';modalLogo.classList.add('visible')}else{modalLogo.classList.remove('visible');modalLogo.removeAttribute('src')}
  if(p.link){modalLink.href=p.link;modalLink.hidden=false;modalLink.textContent=currentLang==='fr'?'Voir sur GitHub →':'View on GitHub →'}else modalLink.hidden=true;
  modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';
}
$$('.details-btn[data-project]').forEach(btn=>btn.addEventListener('click',()=>openProject(btn.dataset.project)));
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}
$('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});
$('#contactForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const subject=encodeURIComponent('Portfolio contact — '+f.get('name'));const body=encodeURIComponent(`Name: ${f.get('name')}\nEmail: ${f.get('email')}\n\n${f.get('message')}`);location.href=`mailto:Fatimaezzahraejami185@gmail.com?subject=${subject}&body=${body}`;});
setLanguage(currentLang);